# Setup
title: Islam Shehata 
tagline: Software Engineer
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://schehata.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Islam Shehata
  url:               https://twitter.com/shehatstein
  email:             schehata@icloud.com

# Custom vars
version:             1.0.0
